[package]
name = "dechst-chunker"
version = "0.1.0"
edition = "2021"

[lib]
name = "dechst_chunker"

[dependencies]
serde = { version = "1.0.126", features = ["derive"], optional = true }

[dev-dependencies]
pretty_assertions = "0.7.2"
rand = "0.8.3"
